network:
  version: 2
  ethernets:
    id0:
      match:
        macaddress: "52:54:00:12:00:02"
      dhcp4: false
      addresses:
        - 192.168.100.12/24
      gateway4: 192.168.100.1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
